Feature 1
simt11/BinInfo pull request #2
Opened 2023-03-03 13:48 UTC by simt11

2023-03-04 10:10 UTC, fantasianna requested changes

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +package com.example.bininfo
есть два способа структурирования исходного кода:
- группировать по фичам (то есть по мейн скрину все в одну папку)
- или группировать по типам
Я вижу что у тебя сделан второй вариант, но не полностью. Вот эта модель, это ответ от сетевого запроса, а значит должна лежать в пакете network, а лежит просо в корне проекта. Так же в корне лежит MainActivity, а она должна лежать скорее всего в ui/screens. Пробегись по всем остальным файлам и проведи ревизию структуры

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +    val number: Number? = null,
здесь не нужно у каждого параметра писать  = null, сериалайзер сам подставит нули, если данные не придут. ППредлагаю убрать  = null, тк это засоряет код и ухудшает читаемость

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/ui/screens/HomeFragment.kt
> +class HomeFragment(context: Context) : Fragment(R.layout.fragment_home) {
если этот фрагмент использует BinViewModel и наверное используется именно для отрисовки БИНов, то имеет смыл его назвать так же как и вью модель, то есть BinFragment, чтобы глядя на на файлы фрагмент и вью модели была сразу очевидна их кармическая связь

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/MainActivity.kt
> +        replaceFragment(HomeFragment(this), false)
зачем тут фрагмент внутри активити? это имело бы смысл, если бы у тебя была смена фрагментов, как в приложении телеграмма. А если у тебя один экран, то это скользкий момент, получается оверинжиниринг в моменте, где по факту это не нужно. Предлагаю избавиться от вложенности фрагмента в активити, и сделать все внутри активити

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +    ) {}
{} - не нужно, удали везде где нет тела

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +        val latitude: Int? = null,
а широта и долгота правда приходят интами? 
я думала у них такой формат: 41.40338, 2.17403

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +    val bank: Bank? = null,
очень подозрительно выглядят контракты, в которых все параметры опциональные? получается вообще никакого контракта взаимодействия с сервером нет и мы не можем быть уверены в приходе вообще никаких парамметров. Обычно контракты составляются таким образом, что у каждого параметра написано, опциональный он или нет, то есть предусматривает ли контракт, что в некоторых случаях параметр не придет или придет со значением null. Я так понимаю что тут нет описания контракта, но все равно делать все параметры опциональными не стоит. Посмотри для разных входных данных, какие параметры могут не прийти, и только их сделай опциональными, а остальные - обязательными

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +    val bank: Bank? = null,
то же актуально для всех моделей ниже

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +    val prepaid: Boolean? = null,
булевы параметры надо начинать с is или has, то есть тут будет isPrepaid, проверь для всех отсальных

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +    val type: String? = null,
тут набор типов не ограничен какими-то значениями? можно сделать енам?

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +        val luhn: Boolean? = null,
это алгоритм Луны?))
кажется читаемее было бы значение isLuhnAlgorithm

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/network/BinApiService.kt
> +    suspend fun getBinInfo(@Path("BIN", encoded = true) BIN: String): BinCard
параметры методов называем маленькими буквами, тут должно быть bin: String

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/res/layout/activity_main.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
не нужно делать вложенные друг в друга ConstraintLayout, они созданы как раз для того, чтобы избежать вложенности внутри себя.
Ты можешь добавить android:id="@+id/dataContainer" к констрейнту верхнего уровня

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/res/layout/fragment_home.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
попробуй запустить свой проект на эмуляторе с маленьким экраном. Насколько я знаю ConstraintLayout не умеет скролится, и если у тебя будет маленький экран, то весь контент на него не влезет и пользователь не увидит низ списка и не сможет просколить вниз. Быстрое решение: поместить ConstraintLayout внутрь ScrollView. Но идеальное решение, это использовать RecyclerView. Этот контейнер используется для 90% экранов на андроиде и с ним тебе все равно придется познакомиться. 
https://habr.com/ru/post/705064/

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
это текст где-то используется?

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/res/values/styles.xml
> +    <style name="text_param">
ты выше использвал камел кейс для именования стилей, тут туже надо продолжить, будет textParam

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/res/values/styles.xml
> +    <style name="answer_param">
и тут

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/utilits/appTextWatcher.kt
> +class appTextWatcher(val onSuccess:(Editable?) -> Unit):TextWatcher {
я чаше встречала названия SimpleTextWatcher для таких реализаций, когда реализуется какая то часть интерфейса. Имена классов всегда начинаются с большой буквы, мы относимся к ним уважительно

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/utilits/appTextWatcher.kt
> +class appTextWatcher(val onSuccess:(Editable?) -> Unit):TextWatcher {
:TextWatcher нужен пробел между

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/utilits/Fun.kt
> +package com.example.bininfo.utilits
этот класс содержит экстеншены, я часто встречала для такого класса название Extensions.kt

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/utilits/Fun.kt
> +    val intent = Intent(Intent.ACTION_DIAL, query)
а пермишены в манифесте объявлены для этого акшена?

2023-03-04 10:10 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/ui/screens/HomeFragment.kt
> +import com.example.bininfo.utilits.hideKeyboard
а где showKeyboard? он не используется в итоге? может удалить его тогда из екстеншенов?

2023-03-04 14:29 UTC, simt11 commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +    val number: Number? = null,
Так вс е равно приложение крашится

2023-03-06 08:40 UTC, simt11 commented on app/src/main/java/com/example/bininfo/MainActivity.kt
> +        replaceFragment(HomeFragment(this), false)
Здесь подразумевается второй фрагмент с историей запросов. Для этого вынес из активити. (Плюс так по привычке сделал :)

2023-03-06 08:42 UTC, simt11 commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +    ) {}
Сделано

2023-03-06 08:42 UTC, simt11 commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +        val latitude: Int? = null,
Да, ты права.

2023-03-06 09:00 UTC, simt11 commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +        val luhn: Boolean? = null,
Я правильно понял, что здесь названия должны полностью совпадать с названиями JSON ответа? А так согласен. Твой вариант более читаемый

2023-03-06 09:01 UTC, simt11 commented on app/src/main/java/com/example/bininfo/network/BinApiService.kt
> +    suspend fun getBinInfo(@Path("BIN", encoded = true) BIN: String): BinCard
Исправил

2023-03-06 09:02 UTC, simt11 commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +package com.example.bininfo
Исправил

2023-03-06 09:02 UTC, simt11 commented on app/src/main/java/com/example/bininfo/ui/screens/HomeFragment.kt
> +class HomeFragment(context: Context) : Fragment(R.layout.fragment_home) {
Исправил

2023-03-06 09:04 UTC, simt11 commented on app/src/main/res/layout/activity_main.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Исправил

2023-03-06 09:05 UTC, simt11 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Убрал этот текст

2023-03-06 09:06 UTC, simt11 commented on app/src/main/res/values/styles.xml
> +    <style name="text_param">
Исправил на камел кейс

2023-03-06 09:07 UTC, simt11 commented on app/src/main/java/com/example/bininfo/utilits/appTextWatcher.kt
> +class appTextWatcher(val onSuccess:(Editable?) -> Unit):TextWatcher {
Отметил себе по названиям. Класс удален, за ненадобностью. Теперь проверка происходит по нажатию

2023-03-06 09:10 UTC, simt11 commented on app/src/main/java/com/example/bininfo/utilits/Fun.kt
> +package com.example.bininfo.utilits
я не понял, для какого класса(((( Или ты имела ввиду название папки?

2023-03-06 09:12 UTC, simt11 commented on app/src/main/java/com/example/bininfo/utilits/Fun.kt
> +    val intent = Intent(Intent.ACTION_DIAL, query)
не объявлены... 
Как я понимаю, здесь не нужны разрешения дополнительные. Потому, что это не звонок по телефону, а только передача номера в звонилку. Фактически приложение не звонит и разрешение поэтому ему не нужно.

2023-03-06 09:12 UTC, simt11 commented on app/src/main/java/com/example/bininfo/ui/screens/HomeFragment.kt
> +import com.example.bininfo.utilits.hideKeyboard
да, ок)

2023-03-06 09:54 UTC, simt11 commented on app/src/main/java/com/example/bininfo/utilits/Fun.kt
> +package com.example.bininfo.utilits
Изменил Fun на Extensions

2023-03-07 09:58 UTC, simt11 commented on app/src/main/res/layout/fragment_home.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Эмулятор с маленьким экраном, не запускаетя(

2023-03-08 11:00 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +        val luhn: Boolean? = null,
да должен совпадать с джейсоном, так что пусть останется как есть

2023-03-08 11:00 UTC, fantasianna commented on app/src/main/res/layout/fragment_home.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
это критическое замечание, надо разобраться, попробуй другое устройство в эмуляторе

2023-03-08 11:01 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/utilits/Fun.kt
> +package com.example.bininfo.utilits
я имела ввиду название файла

2023-03-08 11:03 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/utilits/Fun.kt
> +    val intent = Intent(Intent.ACTION_DIAL, query)
ага поняла хорошо

2023-03-08 11:08 UTC, fantasianna commented on app/src/main/res/layout/fragment_home.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
подумала тут RecyclerView не подойдет, потому что экран формируется статически, нет профита от RecyclerView. но в ScrollView надо завернуть твой ConstraintLayout и провериь на маленьком экране. Так же это можно проверить, если открыть клавиатуру и посмотреть, можешь ли ты проскролить экран вниз

2023-03-08 11:09 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/BinCard.kt
> +    val type: String? = null,
не крит, просто хорошо бы понимать

2023-03-10 09:14 UTC, simt11 commented on app/src/main/res/layout/fragment_home.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Разобрался с проблемами эмулятора. Оказалось, что закончилось место на диске. Как увеличил, так и заработало)))))

2023-03-10 09:15 UTC, simt11 commented on app/src/main/res/layout/fragment_home.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
По поводу скролинга, буду еще разбираться

2023-03-10 13:26 UTC, simt11 commented on app/src/main/res/layout/fragment_home.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Добавил скролинг во фрагмент.

2023-03-13 08:12 UTC, fantasianna approved these changes

2023-03-13 08:12 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/ui/screens/BinFragment.kt
> +                viewModel.getBinInfo(string)
вот это место надо будет переделать, чтобы логику убрать во вью модель, а фрагмент оставить максимально глупым и чтобы он только умел отрисовывать. Сядем вместе потом, когда будет готов поиск

2023-03-13 08:12 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/ui/screens/BinFragment.kt
> +            val Coordinates = binding.answerCoordinates.text.toString()
названия переменных всегда с маленькой буквы

2023-03-13 08:12 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/ui/screens/BinFragment.kt
> +                intentPhone(bankPhone)
логику роутинга тоже надо будет убрать во вью модель, фргамент не должен принимать таких важных решений, в нем вообще не должно быть какой либо логики, кроме отрисовки

2023-03-13 08:12 UTC, fantasianna commented on app/src/main/java/com/example/bininfo/ui/screens/BinFragment.kt
> +        if (preferences.contains(BIN_NUMBER)) {
логику работы с преференсами надо тоже убрать во вью модель

2023-03-13 08:13 UTC, merged

2023-03-13 09:10 UTC, simt11 commented on app/src/main/java/com/example/bininfo/ui/screens/BinFragment.kt
> +            val Coordinates = binding.answerCoordinates.text.toString()
Точно. Копипастил